# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ALPSOccupancyGrid.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ALPSOccupancyGrid.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x17\x41LPSOccupancyGrid.proto\"m\n\x11\x41LPSOccupancyGrid\x12\x15\n\rcellsPerMeter\x18\x01 \x01(\x02\x12\x14\n\x0c\x62ytesPerCell\x18\x02 \x01(\r\x12\r\n\x05width\x18\x03 \x01(\r\x12\x0e\n\x06height\x18\x04 \x01(\r\x12\x0c\n\x04grid\x18\x05 \x01(\x0c\x62\x06proto3'
)




_ALPSOCCUPANCYGRID = _descriptor.Descriptor(
  name='ALPSOccupancyGrid',
  full_name='ALPSOccupancyGrid',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='cellsPerMeter', full_name='ALPSOccupancyGrid.cellsPerMeter', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='bytesPerCell', full_name='ALPSOccupancyGrid.bytesPerCell', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='width', full_name='ALPSOccupancyGrid.width', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='height', full_name='ALPSOccupancyGrid.height', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='grid', full_name='ALPSOccupancyGrid.grid', index=4,
      number=5, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=27,
  serialized_end=136,
)

DESCRIPTOR.message_types_by_name['ALPSOccupancyGrid'] = _ALPSOCCUPANCYGRID
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ALPSOccupancyGrid = _reflection.GeneratedProtocolMessageType('ALPSOccupancyGrid', (_message.Message,), {
  'DESCRIPTOR' : _ALPSOCCUPANCYGRID,
  '__module__' : 'ALPSOccupancyGrid_pb2'
  # @@protoc_insertion_point(class_scope:ALPSOccupancyGrid)
  })
_sym_db.RegisterMessage(ALPSOccupancyGrid)


# @@protoc_insertion_point(module_scope)
